### ISSUE TITLE
Fail on unused "excluded" advisory

### ISSUE THREAD

**Issue by codegain** [djfdyuruiry/improved-yarn-audit#12]
Hi,

would it be possible to add a new flag like "--fail-on-unused-excludes" which causes the command to fail (exit code 1) if there is an advisory excluded which no longer effects the current audit (e.g. the package in question was already updated)?

This could really help me clean-up "old" excluded advisories which no longer affect the current set of packages.

**Comment by djfdyuruiry** [comment]
This sounds like a great little idea. Will let you when it's added

**Comment by djfdyuruiry** [comment]
This feature has been added to v2.2.0, enjoy :+1:
