### ISSUE TITLE
Show package name in output

### ISSUE THREAD

**Issue by jaymefSO** [djfdyuruiry/improved-yarn-audit#17]
This is more of a request than an issue but it would be nice if the output showed the name of the package along with link to the relevant advisory. 

e.x.

instead of:

Vulnerability Found: HIGH     - https://npmjs.com/advisories/xxx

show:

Vulnerability Found: HIGH - package_name - https://npmjs.com/advisories/xxxx

**Comment by djfdyuruiry** [comment]
Sounds sensible enough, I have added this to the v2.3.0 release.
