### ISSUE TITLE
Ignore vulnerabilities in devDependencies

### ISSUE THREAD

**Issue by codegain** [djfdyuruiry/improved-yarn-audit#2]
Hi,

I would like to ignore vulnerabilities in devDependencies as these dependencies are only used on the development machines. Is there any way to ignore all vulnerabilities in devDependencies? (or at least show them, but don't exit with an exit code > 0)

**Comment by djfdyuruiry** [comment]
Hi @codegain 

This is a great suggestion, I have released a `v1.1.0` of the tool that can do exactly this. Simply pass the `--ignore-dev-deps` flag:

```bash
yarn run improved-yarn-audit --ignore-dev-deps
```

Thanks again for the issue, and let me know you have any other queries.
