### ISSUE TITLE
Cannot add an exclusion list for advisories with the GitHub URL

### ISSUE THREAD

**Issue by pavlakis** [djfdyuruiry/improved-yarn-audit#26]
> WARNING: One or more excluded audit advisories were missing from yarn audit output: 1693,1695

Probably as advisories now come from GitHub? `https://github.com/advisories/GHSA-4943-9vgg-gr5r`
But it doesn't allow me to use the `GHSA` identifier and neither the URL.

Is there a workaround to add these to an exclusion list?

**Comment by pavlakis** [comment]
According to [this article](https://github.blog/changelog/2021-10-03-the-npm-advisory-database-is-now-part-of-the-github-advisory-database/) there should be a redirect on npmjs advisories pointing to GitHub - which at present it doesn't seem to be working.

**Comment by pavlakis** [comment]
Redirects work again. This is no longer an issue.

**Comment by pavlakis** [comment]
@firefox0102 it stopped complaining at some point and I left it alone.

But unfortunately today the errors started coming through. So back to square one until the GH advisories are added to the exclusion list.

**Comment by firefox0102** [comment]
I opened a PR to poke around at supporting both the npmjs urls and the new GHSA urls 
https://github.com/djfdyuruiry/improved-yarn-audit/pull/27
