### ISSUE TITLE
Allow excludes to be defined in an ignore file in place of an arg

### ISSUE THREAD

**Issue by benhodgson87** [djfdyuruiry/improved-yarn-audit#4]
Feature request rather than an issue:

Similar to how [publish-please](https://www.npmjs.com/package/publish-please) handles ignoring advisories, it would be nice if advisory codes to be excluded could also be listed in an ignore file (eg. `.auditignore`). This would be handy for version control, putting each ignore code onto it's own line, and would also allow for supplementing codes with commenting, or defining the ignore code as the full npm url (ie. `https://npmjs.com/advisories/12`) - making it easier to quickly track back to an issue.

Happy to look at putting forward a PR for this.

**Comment by djfdyuruiry** [comment]
@benhodgson87  I have released version `v2.0.0` of this package which includes an implementation of your suggestion. See the `.iyarc` section in the README, this should give you what you were looking for. Let me know if this helps you out!
